; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mqtt]
build_flags =
	-D MQTT_HOST=\"10.243.225.129\"
	-D MQTT_PORT=1883
	-D MQTT_CLIENT_ID=\"RobotB1\"
	-D MQTT_USERNAME=\"\"
	-D MQTT_PASSWORD=\"\"
	-D MQTT_PUB_TOPIC=\"esp32/RobotA/serial_out\"
	-D MQTT_CMD_TOPIC=\"esp32/RobotA/serial_in\"
	-D MQTT_HEARTBEAT_TOPIC=\"esp32/commrobot/heartbeat\"
	-D MQTT_RETRY_DELAY_MS=3000
	-D WIFI_DEFAULT_SSID=\"kitakitan\"
	-D WIFI_DEFAULT_PASSWORD=\"bocchichan\"
	-D MQTT_SERIAL_BUFFER=128
build_src_filter = +<**> -<src/tasks/mqtt_task.cpp> -<src/tasks/wifi_task.cpp>
[env:upesy_wroom_receiver]
platform = espressif32
board = upesy_wroom
monitor_speed=115200
framework = arduino
upload_port = /dev/cu.usbserial-11220
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master


[env:nodemcuv2_receiver]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_filters = 
	esp8266_exception_decoder
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:upesy_wroom_transmitter]
platform = espressif32
board = upesy_wroom
monitor_speed=115200
framework = arduino
build_src_filter = +<transmitter/**> +<config/**> -<receiver/**>
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master


[env:nodemcuv2_transmitter]
platform = espressif8266
monitor_filters = 
	esp8266_exception_decoder
board = nodemcuv2
framework = arduino
monitor_speed=115200
build_src_filter = +<transmitter/**> +<config/**> -<receiver/**>
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:arduino_nano_esp32_receiver]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"DefaultRobot\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:arduino_nano_esp32_transmitter]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<transmitter/**> +<config/**> -<receiver/**>
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:node32s_receiver]
platform = espressif32
board = node32s
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"Node32sRobot\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.9
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:node32s_transmitter]
platform = espressif32
board = node32s
framework = arduino
monitor_speed=115200
build_src_filter = +<transmitter/**> +<config/**> -<receiver/**>
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:RobotA]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotA\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.9
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:RobotB1]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotB1\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.9
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:RobotB2]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotB2\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.9
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:RobotC]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotC\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.9
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:RobotD]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotD\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.9
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:nodemcuv2_RobotA]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_filters = 
	esp8266_exception_decoder
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotA\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:nodemcuv2_RobotB1]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_filters = 
	esp8266_exception_decoder
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotB1\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:nodemcuv2_RobotB2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_filters = 
	esp8266_exception_decoder
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotB2\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:nodemcuv2_RobotC]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_filters = 
	esp8266_exception_decoder
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotC\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master

[env:nodemcuv2_RobotD]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_filters = 
	esp8266_exception_decoder
monitor_speed=115200
build_src_filter = +<receiver/**> +<config/**> -<transmitter/**>
build_flags = -D ROBOT_NAME=\"RobotD\"
lib_deps =
	knolleary/PubSubClient @ ^2.8
    git+https://github.com/MyArduinoLib/Arduino-PS2X-ESP32.git#master